import "./styles/main.scss";
import "./assets/logo.svg";
import "./assets/mail.svg";
import "./assets/triangle.svg";
import "./assets/arrow.svg";
import "./assets/hero.jpg";
import "./assets/item1.jpg";
import "./assets/item2.jpg";
import "./assets/item3.jpg";
